version: '3.8'

services:
  iss:
    build: .
    ports:
      - '4000:4000'
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DIRECT_URL: ${DIRECT_URL}
      TRANSAC_AI_RSS_API_KEY: ${TRANSAC_AI_RSS_API_KEY}
